"""Write a fitted block list out as a Studio script, a build sheet, a viewer or raw JSON."""

from __future__ import annotations

import json
from .fitting import Block

MIN_PART_SIZE = 0.05


def block_records(blocks: list[Block]) -> list[dict]:
    """Blocks as plain dicts in stud units, ready for any of the writers below."""
    records = []
    for block in blocks:
        roll, pitch, yaw = block.euler_xyz()
        records.append({
            "position": [round(v, 4) for v in block.center],
            "size": [round(max(v, MIN_PART_SIZE), 4) for v in block.size],
            "rotation": [round(roll, 2), round(pitch, 2), round(yaw, 2)],
            "axes": [round(v, 6) for v in block.u + block.v + block.n],
            "color": "#%02x%02x%02x" % block.color,
        })
    return records


def palette_of(records: list[dict]) -> list[str]:
    seen = {}
    for record in records:
        seen.setdefault(record["color"], 0)
        seen[record["color"]] += 1
    return [color for color, _ in sorted(seen.items(), key=lambda item: -item[1])]


def write_json(path: str, records: list[dict], meta: dict) -> None:
    with open(path, "w", encoding="utf-8") as handle:
        json.dump({"meta": meta, "palette": palette_of(records), "blocks": records},
                  handle, indent=1)


def write_lua(path: str, records: list[dict], name: str = "ImportedBuild",
              material: str = "SmoothPlastic") -> None:
    """A Studio script that rebuilds the model out of anchored parts."""
    palette = palette_of(records)
    index = {color: i + 1 for i, color in enumerate(palette)}

    entries = []
    for record in records:
        # The block's own axes go out as-is; letting Studio rebuild the CFrame from a matrix
        # keeps the rotation exact instead of routing it through an Euler convention.
        numbers = record["position"] + record["size"] + record["axes"][:6]
        entries.append(",".join(str(v) for v in numbers) + f",{index[record['color']]}")

    chunks = [";".join(entries[i:i + 200]) for i in range(0, len(entries), 200)]
    colors = ",\n\t".join(
        "Color3.fromRGB(%d, %d, %d)" % tuple(int(color[i:i + 2], 16) for i in (1, 3, 5))
        for color in palette
    )
    data = ",\n\t".join('"%s"' % chunk for chunk in chunks)

    # Every comment is a block comment: pasting into the Studio command bar can flatten the
    # script onto one line, and a line comment there would swallow the rest of the build.
    script = f'''--[[ Generated by tools/babft_builder from a 3D model.
     Paste into the Roblox Studio command bar (or a Script) and run it.
     Every part is anchored, so the build stays put until you weld or group it yourself. ]]

local SCALE = 1 --[[ multiply every position and size by this ]]
local ORIGIN = Vector3.new(0, 0, 0) --[[ where the build's ground centre lands ]]

local COLORS = {{
\t{colors}
}}

local DATA = {{
\t{data}
}}

local model = Instance.new("Model")
model.Name = "{name}"

local count = 0
for _, chunk in ipairs(DATA) do
\tfor _, entry in ipairs(string.split(chunk, ";")) do
\t\tlocal f = string.split(entry, ",")
\t\tlocal part = Instance.new("Part")
\t\tpart.Anchored = true
\t\tpart.Material = Enum.Material.{material}
\t\tpart.TopSurface = Enum.SurfaceType.Smooth
\t\tpart.BottomSurface = Enum.SurfaceType.Smooth
\t\tpart.Size = Vector3.new(tonumber(f[4]), tonumber(f[5]), tonumber(f[6])) * SCALE
\t\tpart.CFrame = CFrame.fromMatrix(
\t\t\tORIGIN + Vector3.new(tonumber(f[1]), tonumber(f[2]), tonumber(f[3])) * SCALE,
\t\t\tVector3.new(tonumber(f[7]), tonumber(f[8]), tonumber(f[9])),
\t\t\tVector3.new(tonumber(f[10]), tonumber(f[11]), tonumber(f[12])))
\t\tpart.Color = COLORS[tonumber(f[13])]
\t\tpart.Parent = model
\t\tcount += 1
\tend
end

model.Parent = workspace
print(string.format("placed %d parts", count))
'''
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(script)


def write_sheet(path: str, records: list[dict], meta: dict) -> None:
    """A flat build list: one line per block, in the order they should be placed."""
    palette = palette_of(records)
    lines = [
        "# " + meta.get("source", "build"),
        "# size (studs): %.1f x %.1f x %.1f   blocks: %d   colours: %d"
        % (*meta["size"], len(records), len(palette)),
        "# rotation is degrees around X, Y, Z (Roblox CFrame.Angles order)",
        "#",
        "#   n  colour    size w x h x d        position x, y, z          rotation x, y, z",
    ]
    for i, record in enumerate(sorted(records, key=lambda r: (r["position"][1], -max(r["size"]))), 1):
        lines.append(
            "%5d  %s  %7.2f x %6.2f x %6.2f   %8.2f, %7.2f, %8.2f   %7.1f, %6.1f, %7.1f" % (
                i, record["color"], *record["size"], *record["position"], *record["rotation"]))
    lines.append("")
    lines.append("# colour totals")
    counts = {}
    for record in records:
        counts[record["color"]] = counts.get(record["color"], 0) + 1
    for color in palette:
        lines.append("#   %s  %d blocks" % (color, counts[color]))
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines) + "\n")


def write_html(path: str, records: list[dict], meta: dict) -> None:
    """A single-file viewer: orbit the result and step through the build order."""
    payload = json.dumps({"meta": meta, "blocks": records}, separators=(",", ":"))
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(_HTML.replace("__PAYLOAD__", payload))


_HTML = """<!doctype html>
<html lang="ja">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Block build preview</title>
<style>
  :root { color-scheme: dark; }
  body { margin: 0; font: 13px/1.5 system-ui, sans-serif; background: #14161a; color: #e6e8ec;
         display: grid; grid-template-columns: 1fr 320px; height: 100vh; }
  canvas { width: 100%; height: 100%; display: block; cursor: grab; }
  canvas:active { cursor: grabbing; }
  aside { border-left: 1px solid #2a2e36; padding: 14px; overflow-y: auto; }
  h1 { font-size: 15px; margin: 0 0 10px; }
  dl { display: grid; grid-template-columns: auto 1fr; gap: 2px 10px; margin: 0 0 14px; }
  dt { color: #8b93a1; }
  dd { margin: 0; }
  input[type=range] { width: 100%; }
  ol { list-style: none; margin: 8px 0 0; padding: 0; }
  li { display: grid; grid-template-columns: 14px 1fr; gap: 8px; padding: 4px 2px;
       border-top: 1px solid #22262e; font-variant-numeric: tabular-nums; }
  li.on { background: #1d2129; }
  i { width: 12px; height: 12px; border-radius: 2px; display: block; margin-top: 3px; }
  small { color: #8b93a1; display: block; }
  @media (max-width: 720px) { body { grid-template-columns: 1fr; grid-template-rows: 60vh 1fr; }
    aside { border-left: 0; border-top: 1px solid #2a2e36; } }
</style>
</head>
<body>
<canvas id="view"></canvas>
<aside>
  <h1>Block build preview</h1>
  <dl id="stats"></dl>
  <label>build order: <b id="upto"></b></label>
  <input type="range" id="steps" min="1" value="1">
  <ol id="list"></ol>
</aside>
<script>
const DATA = __PAYLOAD__;
const blocks = DATA.blocks;
const canvas = document.getElementById("view");
const ctx = canvas.getContext("2d");
let yaw = 0.7, pitch = 0.5, zoom = 1, shown = blocks.length, hover = -1;

const stats = document.getElementById("stats");
const size = DATA.meta.size.map(v => v.toFixed(1)).join(" x ");
const palette = [...new Set(blocks.map(b => b.color))];
stats.innerHTML = `<dt>source</dt><dd>${DATA.meta.source || "-"}</dd>` +
  `<dt>mode</dt><dd>${DATA.meta.mode}</dd>` +
  `<dt>blocks</dt><dd>${blocks.length}</dd>` +
  `<dt>colours</dt><dd>${palette.length}</dd>` +
  `<dt>size</dt><dd>${size} studs</dd>`;

const list = document.getElementById("list");
list.innerHTML = blocks.map((b, i) =>
  `<li data-i="${i}"><i style="background:${b.color}"></i><span>#${i + 1}
   ${b.size.map(v => v.toFixed(2)).join(" x ")}
   <small>pos ${b.position.map(v => v.toFixed(1)).join(", ")} /
   rot ${b.rotation.map(v => v.toFixed(0)).join(", ")}</small></span></li>`).join("");
list.addEventListener("mousemove", e => {
  const li = e.target.closest("li");
  const i = li ? +li.dataset.i : -1;
  if (i !== hover) { hover = i; draw(); }
});
list.addEventListener("mouseleave", () => { hover = -1; draw(); });

const steps = document.getElementById("steps");
steps.max = blocks.length;
steps.value = blocks.length;
steps.addEventListener("input", () => { shown = +steps.value; draw(); });

canvas.addEventListener("mousedown", down => {
  const start = { x: down.clientX, y: down.clientY, yaw, pitch };
  const move = e => {
    yaw = start.yaw + (e.clientX - start.x) * 0.008;
    pitch = Math.max(-1.5, Math.min(1.5, start.pitch + (e.clientY - start.y) * 0.008));
    draw();
  };
  const up = () => { removeEventListener("mousemove", move); removeEventListener("mouseup", up); };
  addEventListener("mousemove", move); addEventListener("mouseup", up);
});
canvas.addEventListener("wheel", e => {
  e.preventDefault();
  zoom = Math.max(0.2, Math.min(6, zoom * (e.deltaY > 0 ? 0.9 : 1.1)));
  draw();
}, { passive: false });

const CORNERS = [[-1,-1,-1],[1,-1,-1],[1,1,-1],[-1,1,-1],[-1,-1,1],[1,-1,1],[1,1,1],[-1,1,1]];
const FACES = [[0,1,2,3],[5,4,7,6],[4,0,3,7],[1,5,6,2],[3,2,6,7],[4,5,1,0]];

function centre() {
  let lo = [1e9,1e9,1e9], hi = [-1e9,-1e9,-1e9];
  for (const b of blocks) for (let a = 0; a < 3; a++) {
    lo[a] = Math.min(lo[a], b.position[a] - b.size[a]);
    hi[a] = Math.max(hi[a], b.position[a] + b.size[a]);
  }
  return { mid: lo.map((v, i) => (v + hi[i]) / 2), span: Math.max(...hi.map((v, i) => v - lo[i])) || 1 };
}
const view = centre();

function draw() {
  const dpr = devicePixelRatio || 1;
  canvas.width = canvas.clientWidth * dpr;
  canvas.height = canvas.clientHeight * dpr;
  ctx.setTransform(dpr, 0, 0, dpr, 0, 0);
  ctx.clearRect(0, 0, canvas.clientWidth, canvas.clientHeight);

  const w = canvas.clientWidth, h = canvas.clientHeight;
  const scale = Math.min(w, h) / view.span * 0.8 * zoom;
  const cy = Math.cos(yaw), sy = Math.sin(yaw), cp = Math.cos(pitch), sp = Math.sin(pitch);

  const project = p => {
    const x = p[0] - view.mid[0], y = p[1] - view.mid[1], z = p[2] - view.mid[2];
    const rx = x * cy - z * sy, rz = x * sy + z * cy;
    const ry = y * cp - rz * sp, depth = y * sp + rz * cp;
    return [w / 2 + rx * scale, h / 2 - ry * scale, depth];
  };

  const quads = [];
  for (let i = 0; i < Math.min(shown, blocks.length); i++) {
    const b = blocks[i];
    const [ux,uy,uz,vx,vy,vz,nx,ny,nz] = b.axes;
    const [sx,syy,sz] = b.size.map(v => v / 2);
    const points = CORNERS.map(([a, c, d]) => project([
      b.position[0] + ux*a*sx + vx*c*syy + nx*d*sz,
      b.position[1] + uy*a*sx + vy*c*syy + ny*d*sz,
      b.position[2] + uz*a*sx + vz*c*syy + nz*d*sz,
    ]));
    for (const face of FACES) {
      const pts = face.map(k => points[k]);
      const area = (pts[1][0]-pts[0][0])*(pts[2][1]-pts[0][1]) - (pts[1][1]-pts[0][1])*(pts[2][0]-pts[0][0]);
      if (area <= 0) continue;
      const depth = (pts[0][2] + pts[1][2] + pts[2][2] + pts[3][2]) / 4;
      quads.push({ pts, depth, color: b.color, shade: 0.55 + 0.45 * Math.min(1, area / 4000), i });
    }
  }
  quads.sort((a, b) => a.depth - b.depth);

  for (const q of quads) {
    ctx.beginPath();
    ctx.moveTo(q.pts[0][0], q.pts[0][1]);
    for (let k = 1; k < 4; k++) ctx.lineTo(q.pts[k][0], q.pts[k][1]);
    ctx.closePath();
    ctx.fillStyle = q.i === hover ? "#ff5f6d" : tint(q.color, q.shade);
    ctx.fill();
    ctx.strokeStyle = "rgba(0,0,0,.35)";
    ctx.stroke();
  }
  document.getElementById("upto").textContent = `${Math.min(shown, blocks.length)} / ${blocks.length}`;
  for (const li of list.children) li.classList.toggle("on", +li.dataset.i < shown);
}

function tint(hex, factor) {
  const n = parseInt(hex.slice(1), 16);
  const c = [(n >> 16) & 255, (n >> 8) & 255, n & 255].map(v => Math.round(Math.min(255, v * factor)));
  return `rgb(${c[0]},${c[1]},${c[2]})`;
}

addEventListener("resize", draw);
draw();
</script>
</body>
</html>
"""
